### ISSUE TITLE
rename and combine "util" and "information"

### ISSUE THREAD

**Issue by shanest** [CLMBRs/ultk#14]
`altk.effcomm.util` could be more descriptively named, e.g. `prob` or `probability`.  Since it also does contain basics from information theory (entropy, mutual info, etc), it also could be called `information`.  I'd then rename `information` to either `ib` or maybe `rate_distortion`

**Comment by nathimel** [comment]
Addressed in [pull request 25](https://github.com/CLMBRs/ultk/pull/25)
